name: vex-templates

on:
  push:
    tags:
      - v*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm install
    - run: npm install -g @angular/cli
    - run: npm run build:prod
    - name: build and deploy
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
          image: ${{ secrets.DOCKER_USERNAME }}/com.vex.templates_vex-templates
          tags: vR5i6io3mbdi4c8gcGe9A4L
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: helm update
      run: |
          # update the helm file
          sed -i 's/:v.*/:vR5i6io3mbdi4c8gcGe9A4L/g' helm/templates/service-gen-deployment.yaml

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.VGITHUB_TOKEN }}
        author_name: Virtuan
        directory: helm
        message: Updating docker tag
        branch: main
